### ISSUE TITLE
какой же говнокод)

### ISSUE THREAD

**Issue by Lightning-py** [AkaiRep/video-to-ascii#3]
Чувак, потрудись хоть пробелы между словами ставить. Конечно на производительность не влияет, но код нечитаемый от слова совсем. И еще, мне просто интересно зачем вот это `from time import sleep as sleep` ? Что оно по твоему вообще должно делать? А так крутой чел, неплохо. Ради бога, исправь форматирование, я тебя просто умоляю.

**Comment by AkaiRep** [comment]
Not a issue

**Comment by FrameMuse** [comment]
У меня то же мнение на этот счёт, но всё же осуждаю использование не профессиональной этики.

**Comment by AkaiRep** [comment]
ладно на самом деле согласен
