### ISSUE TITLE
Изображение подпрыгивает

### ISSUE THREAD

**Issue by FrameMuse** [AkaiRep/video-to-ascii#6]

**Comment by MAaxim91** [comment]
А поподробнее можно? Подпрыгивает всегда или после ресайза? Перевод каретки не помог? Используется нативный cmd или какой-то кастомный терминал?

**Comment by MAaxim91** [comment]
@FrameMuse Возможно, у тебя не установлено обновление Windows KB101875, которое включает поддержку анси последовательностей в консоли. Попробуй изменить переменную `use_ansi_escape_sequences` на _False_ и запустить снова.

**Comment by AkaiRep** [comment]
Issue fixed
