### ISSUE TITLE
Translation to English (Перевод на английский)

### ISSUE THREAD

**Issue by ShadowOfPripyat** [AkaiRep/video-to-ascii#9]
Translate readme.md to make instructions readable by anyone.

**Comment by BlaizerBrumo** [comment]
![](https://komarev.com/ghpvc/?username=AkaiRep-video-to-ascii)

TRANSLATED BY [BlaizerBrumo](https://github.com/BlaizerBrumo)
========================

video-to-ascii
========================
The script which shows the video on the console. Nothing extra)
## Installation of Python
* Install Python 3.10 from this site ["click"](https://www.python.org/ftp/python/3.10.1/python-3.10.1-amd64.exe)
## Installations
```
pip install opencv-python
pip install Pillow
```
## Requirements
* Minimum screen resolution: ```1280x720```
* Video in quality ```360p 10-45fps```
* Good mood :)
## Launching
1. Download the zip folder with the script
2. Un-zip the folder with the script anywhere
3. Download the video in the folder with the script
4. Launch CMD (Windows+R > cmd)
5. Open console and go to the folder with the script ```cd "FilePath to the script"```
6. Run script ```python video-to-ascii.py``` ^_^
7. Select downloaded video from the list
8. Vibe

Download
[README-english.md](https://github.com/AkaiRep/video-to-ascii/files/7800678/README-english.md)

**Comment by FrameMuse** [comment]
@BlaizerBrumo do a pull request with that

**Comment by AkaiRep** [comment]
trasnlated
